import type { Metadata } from "next";
import { Geist, Geist_Mono,Inter,Jersey_10} from "next/font/google";
import "./globals.css";
import { Provider } from "@/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const pixelf = Jersey_10({
subsets: ['latin'],
variable: '--font-pixel',
weight: ['400'] 
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} ${pixelf.variable} antialiased`}
      >
        <Provider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange

        >
        {children}
        </Provider>
      </body>
    </html>
  );
}
